'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empleados
    Public Property IdPersonas As Integer
    Public Property Nombre As String
    Public Property Apellidos As String
    Public Property FechaNacimiento As Nullable(Of Date)
    Public Property IdSexo As Nullable(Of Integer)

    Public Overridable Property Sexo As Sexo

End Class
